// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'FirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'FirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: 'your_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'your_project_id',
    authDomain: 'your_auth_domain',
    storageBucket: 'your_storage_bucket',
    measurementId: 'your_measurement_id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: 'your_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'your_project_id',
    storageBucket: 'your_storage_bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: 'your_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'your_project_id',
    storageBucket: 'your_storage_bucket',
    iosClientId: 'your_ios_client_id',
    iosBundleId: 'your_ios_bundle_id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: 'your_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'your_project_id',
    storageBucket: 'your_storage_bucket',
    iosClientId: 'your_ios_client_id',
    iosBundleId: 'your_ios_bundle_id',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: 'your_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'your_project_id',
    storageBucket: 'your_storage_bucket',
  );
}
